# Generated by Django 5.1.5 on 2025-02-09 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('product_details', models.TextField()),
                ('main_price', models.IntegerField()),
                ('Discount', models.IntegerField(blank=True, null=True)),
                ('final_price', models.IntegerField()),
                ('brand', models.CharField(max_length=255)),
                ('brand_image_src', models.URLField()),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('category_image_src', models.URLField()),
                ('size', models.CharField(max_length=50)),
                ('production_date', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productImageSrc', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='App.product')),
            ],
        ),
    ]
