# Generated by Django 5.1.5 on 2025-02-09 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_details',
            new_name='products_details',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='products_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='production_date',
            new_name='productsion_date',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='productImageSrc',
            new_name='productsImageSrc',
        ),
    ]
