# Generated by Django 5.1.5 on 2025-02-09 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_rename_product_details_product_products_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productsion_date',
            new_name='production_date',
        ),
    ]
