# Generated by Django 5.1.5 on 2025-02-09 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_productsion_date_product_production_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products_details',
            new_name='product_details',
        ),
    ]
