# Generated by Django 5.1.5 on 2025-02-09 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_products_details_product_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products_name',
            new_name='product_name',
        ),
    ]
