# Generated by Django 5.1.5 on 2025-02-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_confirm_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirm_code',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
    ]
